### ISSUE TITLE
Which version of Jhipster does the latest generator-jhipster-multitenancy (2.0.0) work with?

### ISSUE THREAD

**Issue by hepaestus** [sonalake/generator-jhipster-multitenancy#103]
I have conflicting build and I think its a version issue. Can you verifiy the version of JHipster that the 2.0.0 version of multitenancy blueprint works with?
Thanks!

**Comment by hepaestus** [comment]
I am seeing in the Package.json file that generator-jhipster-multitenancy uses jhipster-generator version 6.2.0.  Is this the only version it is compatible with?

**Comment by CharlotteFawsitt** [comment]
HI, at the moment we only support 6.2.0. We will be updating to support the latest JHipster version in the next update.
