### ISSUE TITLE
Vuejs Multitenancy support

### ISSUE THREAD

**Issue by yacosta738** [sonalake/generator-jhipster-multitenancy#123]
Do you have plans to support multitenancy with vuejs ?. Currently the option to use vuejs is through a blueprint as well as the option to create the multitenant database. The problem is that if you use both blueprints at the same time the resulting application does not work correctly. Greetings good job.

**Comment by jduggan83** [comment]
Hi @yuniel-acosta Yes we do have plans to support vuejs. Our next priority is to provide support for the latest version of JHipster and then we will look into incorporating vuejs into the blueprint. Our approach will be to first fix any issues arising from running the 2 blueprints concurrently, and then write any custom vuejs code required. Any help on this would be much apprecitated.
