### ISSUE TITLE
Import existing jdl which contains application config

### ISSUE THREAD

**Issue by vrijmetse** [sonalake/generator-jhipster-multitenancy#132]
I tried to generate application using jhipster import-jdl myfile.jdl --blueprints multitenancy but it does not generate an actual application eventhough it says exit code 0.

Is this expected or I miss out anything ?

**Comment by jduggan83** [comment]
Hi @vrijmetse,

You will have to do this in 2 steps:

- First generate the app using: 
`jhipster --blueprints  multitenancy`

- Then run the import-jdl command

**Comment by jduggan83** [comment]
Closing this issue with solution on how to use above.
