### ISSUE TITLE
I am using filters with serviceImpl (DTO mapstruct) along with this blueprint, In method {Entity}QueryService.createSpecification(...) did not addd CompanyId specification 

### ISSUE THREAD

**Issue by jgdvarun60** [sonalake/generator-jhipster-multitenancy#138]

**Comment by jduggan83** [comment]
Hi @jgdvarun60 Can I get some more information on this issues, I don't really understand. Can you give some more information on this?

Perhaps, you could send on your yo-rc.json and your jdl file, if you used one.

**Comment by jgdvarun60** [comment]
This was a corner condition, I was trying with client and server separate latest jhipster version for  redis cache works with latest, and in my case then, it did not add below lines 
..
`
   if (criteria.getOrganizationId() != null) {
                specification = specification.and(buildSpecification(criteria.getOrganizationId(),
                    root -> root.join(Pa_.organization, JoinType.LEFT).get(Organization_.id)));
            }
`

now I am unable to reproduce with fresh jdl import, hence closing

**Comment by jduggan83** [comment]
Thanks for the detail @jgdvarun60
