### ISSUE TITLE
Don't generate the User Entity (jpa entity domain, reposity and service) when the OIDC option is selected.

### ISSUE THREAD

**Issue by maznag** [sonalake/generator-jhipster-multitenancy#17]
The User jpa entity domain is not used  in a JHipster application with OpenId Connect.  It is not necessary to add the default multitenancy filters to the user class.

**Comment by jduggan83** [comment]
Hi @maznag,

Yes this is a good point. We can include this logic, or if you want put this in and create a PR we can include it in the next release.

Jonathan

**Comment by maznag** [comment]
Hi @jduggan83 

OK. I will see if I have free time, I will propose a PR to fix this issue. 

I have a question, does this module works in Microservices application knowing that there is no concept of relationship between different database.

Mus

**Comment by alexander-ozkan** [comment]
@maznag Can this issue be closed as this module does not support the microservices structure.

**Comment by maznag** [comment]
@alexander-ozkan Yes of course.
