### ISSUE TITLE
Support of HttpClientModule

### ISSUE THREAD

**Issue by shwabnitz** [sonalake/generator-jhipster-multitenancy#30]
With JHipster 4.14.0 the old Angular HttpModule (@angular/html) is replaced by the new HttpClientModule (@angular/common/html). The generated entity components look now differently.

The latest version of the multitenancy modul (0.9.6) generates its components still with the old HttpModule.

**Comment by jduggan83** [comment]
Hi @shwabnitz 
Thanks for creating this. Hope to get a fix for this in the next week.

**Comment by alexander-ozkan** [comment]
@shwabnitz We have just released v1.0.0 of our module. This issue has been fixed for the latest version of JHipster -v5.1.0.
