### ISSUE TITLE
ERROR! Can't read .yo-rc.json

### ISSUE THREAD

**Issue by qp06** [sonalake/generator-jhipster-multitenancy#31]
I would like to use this generator. I installed everything as per the instructions on my mac (yo and the generators are installed globally). "yo jhipster" works fine, I created a new folder and when I try "yo jhipster-multitenancy" it is giving me the following error.

Error jhipster-multitenancy 

ERROR! Can't read .yo-rc.json

I tried to generate the project on my Windows computer and got the same error.

**Comment by ciarant** [comment]
Hi, I'm unable to reproduce the issue. Can you share the steps you followed (exactly as you typed them on the command line)?

**Comment by qp06** [comment]
I did a mistake, I thought this will generate the new project didn't realize that I have to generate the project first using jhipster and then run this generator. Closing the issue.

**Comment by ciarant** [comment]
That's great - thanks for closing the issue.
