### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by jeremyprioux** [sonalake/generator-jhipster-multitenancy#40]
When running the module on a freshly created jhipster app (5.2) with **React** frontend, I have the following : 

`ERROR! This module currently only supports Angular 4+`

**Comment by jduggan83** [comment]
Hi @jeremyprioux 

Thanks for the message. Adding support for React is something we hope to deliver in the near future. We are currently looking at what is involved in this piece of development.

**Comment by jeremyprioux** [comment]
Hi, thanks for the response.
It is something I need for my app so I will have a look too. I'm new to jHipster so I can't commit mysel on being able to contribute to the generator in the next weeks/months :).

**Comment by jduggan83** [comment]
Hi @amirensit This module supports Angular 6. Can you please share the .yo-rc.json file of your JHipster application so I can debug.

**Comment by amirensit** [comment]
@jduggan83 thanks for your reply.
In fact, I am using a micro service architecture using jhipster. It has been a month since I started a Saas solution using multi tenancy.
I used this generator in a Jhipster UAA project. I don't know If It really works.
Any way here is  my **.yo-rc.json** file: 
```
 {
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.uaaserver.app"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "uaa",
    "baseName": "uaaServer",
    "packageName": "com.uaaserver.app",
    "packageFolder": "com/uaaserver/app",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ffe2604be535e6998217648b077caa8aa8a38866",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true
  }
} 
```

**Comment by jduggan83** [comment]
Ah I see. Yes this module currently doesn't have support for a microservices architecture. You mentioned you are using Angular6 but presumably so that is not part of your JHipster generated app? The multitenancy module is looking for the property "clientFramework" from your yo-rc.json and checking for the value "angularX". The "clientFramework" property is not present in a microservice app configuration file.

**Comment by amirensit** [comment]
ok thanks. So, do you have any idea how to implement multi tenancy  in a jhipster microservice architecture using spring security oauth ?

**Comment by jduggan83** [comment]
We are hoping to add this support in the future. For now, I would suggest creating a sample monolithic application and then run the multitenancy module on it. Have a look at additional code it provides and see how you can apply this to your existing microservices app.

**Comment by amirensit** [comment]
@jduggan83 ok thanks :)

**Comment by Gabber** [comment]
Hi guys, so if I'm understanding properly there is no way to run the plugin only on the backend and in case of a React frontend implements the changes needed manually

**Comment by CharlotteFawsitt** [comment]
The latest release now includes support for React
