### ISSUE TITLE
Your generated project used a JHipster version (5.0.0) that is currently not supported.)

### ISSUE THREAD

**Issue by somejavadev** [sonalake/generator-jhipster-multitenancy#41]
Hi, 
I see with release v1.0.1 The merge request was `Feature/compatibility 5.2`. I am getting the following error when I run  ``yo jhipster-multitenancy``: 

> Yourgenerated project used a JHipster version (5.0.0) that is currently not supported.)

Is jhipster v5.0.0 supported? I installed the genereator with `npm install -g generator-jhipster-multitenancy`

**Comment by jduggan83** [comment]
Hi @somejavadev 
Sorry for the delay. Yes currently we support  5.1.0, 5.2.0, and 5.2.1. New release coming soon with support for the latest jhipster.
