### ISSUE TITLE
Are there any goals/plans to produce a PR back to the hipster project itself ?

### ISSUE THREAD

**Issue by windbender** [sonalake/generator-jhipster-multitenancy#45]

**Comment by ciarant** [comment]
We haven't raised the idea with the JHipster team. Do you see advantages to providing multitenancy support directly within JHipster as opposed to via a JHipster module?

**Comment by ciarant** [comment]
Yeah - it's difficult for us to say up to date with latest JHipster developments. This is a side-project for us and sometimes work takes priority. We're always looking for contributors though ;-)

**Comment by jduggan83** [comment]
@windbender Im going to close this issue. As you may have seen, we have been quite busy recently with converting this to a blueprint and adding REACT support. We dont have plans in the near future to create a PR to merge into the JHispter project, but you never know. thanks
