### ISSUE TITLE
jhipster-multi tenancy ERROR! Can't read .yo-rc.json

### ISSUE THREAD

**Issue by zsliu** [sonalake/generator-jhipster-multitenancy#46]
After I install generator-jhipster-multitenancy, and run yo jhipster-multitenancy, it gives error as below, please advise

⋊> ~/d/g/k/jhipster-tenant npm install -g generator-jhipster-multitenancy

+ generator-jhipster-multitenancy@1.0.1
updated 1 package in 11.027s
⋊> ~/d/g/k/jhipster-tenant
⋊> ~/d/g/k/jhipster-tenant
⋊> ~/d/g/k/jhipster-tenant yo jhipster-multitenancy
Error jhipster-multitenancy

ERROR! Can't read .yo-rc.json
⋊> ~/d/g/k/jhipster-tenant jhipster-multitenancy
fish: Unknown command 'jhipster-multitenancy'
⋊> ~/d/g/k/jhipster-tenant yo jhipster-multitenancy

Error jhipster-multitenancy

ERROR! Can't read .yo-rc.json

**Comment by zsliu** [comment]
I realize the command need to run under existing apps. But then run into another issue with jhipster version. When can this module support jhipster 5.7.0?

ERROR!
Your generated project used a JHipster version (5.7.0) that is currently not supported.)

**Comment by jduggan83** [comment]
Thanks @zsliu. We're struggling to make the time to keep our multitenancy module up to date with the pace of JHipster development. We are hoping to bring support for the latest version of JHipster very soon. If you are interested in contributing to development, please let me know.
