### ISSUE TITLE
Filter not working for /entity/1

### ISSUE THREAD

**Issue by jduggan83** [sonalake/generator-jhipster-multitenancy#7]
- A user can access an entity from a different tenant by changing the entity id in the url
- e.g. /#/foo/2 where foo of id 2 is not associated with the users tenant.
- Doing this should return a 404
- The filter is being applied but not filtering the result

**Comment by berkaybayraktar** [comment]
Hi, I found that `@Filter` annotation is not applied on functions of **org.springframework.data.repository.CrudRepository**. So, I implemented following code that overrides ``findOne`` function and retrieves data with ``findOneById`` function which is tecniquelly equivalent of ``findOne`` function. Maybe the generator can add this function to repository classes.

Firsty, I created a repository interface called TenantFilterRepository.



Example code of ``FooRepository.java``
```java
/**
 * Spring Data JPA repository for the Foo entity.
 */
@SuppressWarnings("unused")
@Repository
public interface FooRepository extends JpaRepository<Foo, Long> {

    @Override
    default Foo findOne(Long id){
        return this.findOneById(id);
    }

    Foo findOneById(Long id);

}

```

**Comment by berkaybayraktar** [comment]
Hi, I found that

**Comment by berkaybayraktar** [comment]
Hi, I found that ``@Filter`` tag is not applied on **org.springframework.data.repository.CrudRepository** functions. To fix this issue, I created a repository called **TenantFilterRepository** and override ``CrudRepository.findOne`` function on it.

Code of **TenantFilterRepository.java**
```java
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.NoRepositoryBean;

@NoRepositoryBean
public interface TenantFilterRepository<T> extends JpaRepository<T, Long> {

    @Override
    default T findOne(Long id){
        return this.findOneById(id);
    }

    T findOneById(Long id);
}
```
Then, I extend all repositories created by jHipster with TenantFilterRepository.

Code of **FooRepository.java**
```java
/**
 * Spring Data JPA repository for the Fooentity.
 */
@SuppressWarnings("unused")
@Repository
public interface FooRepository extends JpaRepository<Foo, Long>, TenantFilterRepository<Foo> {

}

```

By this way, ``@Filter`` is applied on **findOne** function.

**Comment by jduggan83** [comment]
Hi @berkaybayraktar,

Thanks for this. I will have a look at how the code above can be templated and brought into the generator. The issue with this may be enforcing that all repositories extend TenantFilterRepository<T> when running the module on an application, but I will look into it. 
For now, it is a pretty good workaround for once the module is run on an your jhipster app.

**Comment by alexander-ozkan** [comment]
@berkaybayraktar This issue has been resolved in the latest version.
Thanks.
