### ISSUE TITLE
Blueprint does not create elastic Search annotation in entities properly

### ISSUE THREAD

**Issue by hepaestus** [sonalake/generator-jhipster-multitenancy#97]
When I create entities they do not follow the yo-rc.json file and respond to the "searchEngine":"elasticSearch" setting properly.

**Comment by CharlotteFawsitt** [comment]
Hi, we will look into fixing this issue.

**Comment by BLKingLLC** [comment]
@CharlotteFawsitt You can close this issue, the error was on my end.  My .yo-rc.json was mis-configured.

**Comment by CharlotteFawsitt** [comment]
Perfect! I had just started to look at this today. Thank you for letting me know.
